import { motion } from 'framer-motion'
import { useState } from 'react'
import { BUGS, CATCH_STREAK, bugScienceName, summariseBugs } from '../engine/bugs'
import { SKILL_BY_ID } from '../engine/skills'
import { useGame } from '../state/store'
import { BugCreature } from './BugCreature'
import { Icon } from './Icon'
import { Button, Card, Chip, Kicker } from './ui'

/**
 * The Bug Jar.
 *
 * Every creature here was generated by something this particular child
 * actually did. No two collections are the same, and none of it is
 * authored content.
 */
export function BugJar() {
  const bugs = useGame((s) => s.bugs)
  const setScreen = useGame((s) => s.setScreen)
  const [sel, setSel] = useState<string | null>(null)

  const sum = summariseBugs(bugs)
  const selected = sel ? BUGS.find((b) => b.id === sel) : null
  const selState = sel ? bugs[sel] : undefined

  return (
    <div className="paper-dots scroll min-h-0 flex-1 px-6 pb-8">
      <div className="mx-auto flex max-w-5xl flex-col gap-4 pt-4">
        <div className="flex flex-wrap items-baseline gap-3">
          <h1 className="font-display text-3xl font-black tracking-tight">My Bug Jar</h1>
          <span className="text-sm text-ink-mid">
            Every bug is a mistake you made. Catch them all!
          </span>
          <Button className="ml-auto" size="sm" icon="back" onClick={() => setScreen('forge')}>
            Back to playing
          </Button>
        </div>

        <div className="flex flex-wrap gap-2.5">
          <Chip color="leaf"><Icon name="check" size={15} strokeWidth={3} /> {sum.caught} caught</Chip>
          <Chip color="tomato"><Icon name="flame" size={15} strokeWidth={2.6} /> {sum.loose} still loose</Chip>
          <Chip>{sum.undiscovered} never met</Chip>
        </div>

        <div className="grid gap-4 sm:grid-cols-3 lg:grid-cols-5">
          {BUGS.map((b, i) => {
            const st = bugs[b.id]
            const met = !!st
            const caught = st?.caught ?? false
            return (
              <motion.button
                key={b.id}
                initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }}
                transition={{ delay: i * 0.03, type: 'spring', stiffness: 380, damping: 24 }}
                whileHover={met ? { y: -5 } : undefined}
                onClick={() => met && setSel(sel === b.id ? null : b.id)}
                className={`ink-thick hard-3 pressable flex flex-col items-center gap-1.5 rounded-blob px-3 py-4
                            ${caught ? 'bg-card' : met ? 'bg-shade' : 'bg-shade opacity-60'}
                            ${sel === b.id ? 'ring-4 ring-ink ring-offset-4 ring-offset-paper' : ''}`}
              >
                <BugCreature species={b} size={82} caught={caught} silhouette={!met} animate={met} />
                <div className="font-display text-sm font-black">
                  {met ? b.name : '???'}
                </div>
                {met && !caught && (
                  <div className="flex gap-1">
                    {Array.from({ length: CATCH_STREAK }).map((_, k) => (
                      <span
                        key={k}
                        className={`h-2.5 w-2.5 rounded-full border-2 border-ink
                                    ${k < (st?.streak ?? 0) ? 'bg-leaf' : 'bg-paper'}`}
                      />
                    ))}
                  </div>
                )}
                {caught && <Kicker>caught!</Kicker>}
              </motion.button>
            )
          })}
        </div>

        {selected && selState && (
          <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }}>
            <Card className="flex flex-wrap items-center gap-5 p-5">
              <BugCreature species={selected} size={96} caught={selState.caught} />
              <div className="min-w-56 flex-1">
                <h3 className="font-display text-2xl font-black">{selected.name}</h3>
                <p className="mt-1 text-base leading-snug text-ink-mid">{selected.blurb}</p>
                <div className="mt-3 flex flex-wrap gap-2">
                  <Chip>bit you {selState.seen} time{selState.seen === 1 ? '' : 's'}</Chip>
                  <Chip>lives in {SKILL_BY_ID[selState.skillId]?.label ?? selState.skillId}</Chip>
                </div>
                {!selState.caught && (
                  <p className="mt-3 font-display text-sm font-extrabold text-ink">
                    Get {CATCH_STREAK} right in a row on {SKILL_BY_ID[selState.skillId]?.label} to catch it!
                    ({selState.streak}/{CATCH_STREAK})
                  </p>
                )}
                {/* The grown-up name, kept quiet but present. */}
                <Kicker className="mt-3">Grown-ups call this: {bugScienceName(selected.id)}</Kicker>
              </div>
            </Card>
          </motion.div>
        )}

        {sum.caught === 0 && sum.loose === 0 && (
          <Card tone="shade" className="p-6 text-center">
            <p className="font-display text-lg font-black">Your jar is empty!</p>
            <p className="mt-1 text-sm text-ink-mid">
              Bugs pop out when you make a mistake. Keep playing and you will meet some.
            </p>
          </Card>
        )}
      </div>
    </div>
  )
}
